#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ACTIVE_DIR="$ROOT_DIR/projects/sites/active"
OUT_DIR="$ROOT_DIR/pages_dist"

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

# Build all active sites and copy their dist into pages_dist/<slug>/
for site in "$ACTIVE_DIR"/*; do
  [ -d "$site" ] || continue
  slug="$(basename "$site")"
  echo "==> Building $slug"

  pushd "$site" >/dev/null

  # If package-lock exists we can use npm ci for reproducibility.
  if [ -f package-lock.json ]; then
    npm ci --silent
  else
    npm install --silent
  fi

  npm run build

  if [ ! -d dist ]; then
    echo "ERROR: $slug did not produce dist/" >&2
    exit 1
  fi

  mkdir -p "$OUT_DIR/$slug"
  cp -R dist/* "$OUT_DIR/$slug/"

  popd >/dev/null

done

# Simple index page that links to each site
{
  echo '<!doctype html>'
  echo '<html lang="it">'
  echo '<head><meta charset="utf-8" /><meta name="viewport" content="width=device-width,initial-scale=1" />'
  echo '<title>OpenClaw · Sites (Active)</title>'
  echo '<style>body{font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Ubuntu;max-width:960px;margin:40px auto;padding:0 16px}a{color:#111}li{margin:10px 0}.tag{display:inline-block;padding:2px 10px;border:1px solid #ddd;border-radius:999px;font-size:12px;margin-left:10px;color:#555}</style>'
  echo '</head><body>'
  echo '<h1>Sites (Active)</h1>'
  echo '<p>Build output generated by <code>scripts/pages-build.sh</code>.</p>'
  echo '<ul>'
  for site in "$ACTIVE_DIR"/*; do
    [ -d "$site" ] || continue
    slug="$(basename "$site")"
    echo "<li><a href=\"./$slug/\">$slug</a><span class=\"tag\">active</span></li>"
  done
  echo '</ul>'
  echo '</body></html>'
} > "$OUT_DIR/index.html"

echo "DONE: $OUT_DIR"